// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpf                  string               `protobuf:"bytes,3,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Birthdate            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48c37af7f888781, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCpf() string {
	if m != nil {
		return m.Cpf
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBirthdate() *timestamp.Timestamp {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "users.User")
}

func init() { proto.RegisterFile("users/users.proto", fileDescriptor_b48c37af7f888781) }

var fileDescriptor_b48c37af7f888781 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0x49, 0x6f, 0x2b, 0xdc, 0x11, 0xfc, 0x19, 0x5c, 0x84, 0xbb, 0xb1, 0xb8, 0xea, 0x2a,
	0x05, 0xdd, 0xe8, 0xd2, 0x57, 0x28, 0xba, 0x96, 0xb4, 0x99, 0xd6, 0x40, 0x63, 0x4a, 0x32, 0x7d,
	0x46, 0x5f, 0x4b, 0x9c, 0x5a, 0x5c, 0xde, 0x4d, 0x38, 0xe7, 0xcb, 0x19, 0xf8, 0xe0, 0x76, 0xcd,
	0x94, 0x72, 0x2b, 0xaf, 0x59, 0x52, 0xe4, 0x88, 0x95, 0x94, 0xd3, 0xfd, 0x14, 0xe3, 0x34, 0x53,
	0x2b, 0xb0, 0x5f, 0xc7, 0x96, 0x7d, 0xa0, 0xcc, 0x36, 0x2c, 0xdb, 0xee, 0xe1, 0x5b, 0x41, 0xf9,
	0x9e, 0x29, 0xe1, 0x15, 0x14, 0xde, 0x69, 0x55, 0xab, 0xe6, 0xd8, 0x15, 0xde, 0x21, 0x42, 0xf9,
	0x65, 0x03, 0xe9, 0x42, 0x88, 0x64, 0xbc, 0x81, 0xc3, 0xb0, 0x8c, 0xfa, 0x20, 0xe8, 0x37, 0xe2,
	0x1d, 0x54, 0x14, 0xac, 0x9f, 0x75, 0x29, 0x6c, 0x2b, 0xf8, 0x0c, 0xc7, 0xde, 0x27, 0xfe, 0x74,
	0x96, 0x49, 0x57, 0xb5, 0x6a, 0x2e, 0x1f, 0x4f, 0x66, 0x33, 0x31, 0xbb, 0x89, 0x79, 0xdb, 0x4d,
	0xba, 0xff, 0x31, 0xbe, 0x00, 0x0c, 0x89, 0x2c, 0x93, 0xfb, 0xb0, 0xac, 0xaf, 0xcf, 0x9f, 0xfe,
	0xad, 0x5f, 0xb9, 0xbf, 0x90, 0xef, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x71, 0xb1,
	0x35, 0x0d, 0x01, 0x00, 0x00,
}
