// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN EventType = 0
	EventType_ACCOUNT_CREATED    EventType = 1
)

var EventType_name = map[int32]string{
	0: "EVENT_TYPE_UNKNOWN",
	1: "ACCOUNT_CREATED",
}

var EventType_value = map[string]int32{
	"EVENT_TYPE_UNKNOWN": 0,
	"ACCOUNT_CREATED":    1,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNKNOWN CommandType = 0
)

var CommandType_name = map[int32]string{
	0: "COMMAND_TYPE_UNKNOWN",
}

var CommandType_value = map[string]int32{
	"COMMAND_TYPE_UNKNOWN": 0,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

type ErrorKind int32

const (
	ErrorKind_KIND_NOT_GIVEN ErrorKind = 0
	ErrorKind_BAD_REQUEST    ErrorKind = 400
	ErrorKind_UNAUTHORIZED   ErrorKind = 401
	ErrorKind_NOT_FOUND      ErrorKind = 404
	ErrorKind_UNEXPECTED     ErrorKind = 500
)

var ErrorKind_name = map[int32]string{
	0:   "KIND_NOT_GIVEN",
	400: "BAD_REQUEST",
	401: "UNAUTHORIZED",
	404: "NOT_FOUND",
	500: "UNEXPECTED",
}

var ErrorKind_value = map[string]int32{
	"KIND_NOT_GIVEN": 0,
	"BAD_REQUEST":    400,
	"UNAUTHORIZED":   401,
	"NOT_FOUND":      404,
	"UNEXPECTED":     500,
}

func (x ErrorKind) String() string {
	return proto.EnumName(ErrorKind_name, int32(x))
}

func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

type ErrorSeverity int32

const (
	ErrorSeverity_SEVERITY_NOT_GIVEN ErrorSeverity = 0
	ErrorSeverity_INFO               ErrorSeverity = 1
	ErrorSeverity_WARNING            ErrorSeverity = 2
	ErrorSeverity_ERROR              ErrorSeverity = 3
	ErrorSeverity_CRITICAL           ErrorSeverity = 4
)

var ErrorSeverity_name = map[int32]string{
	0: "SEVERITY_NOT_GIVEN",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
	4: "CRITICAL",
}

var ErrorSeverity_value = map[string]int32{
	"SEVERITY_NOT_GIVEN": 0,
	"INFO":               1,
	"WARNING":            2,
	"ERROR":              3,
	"CRITICAL":           4,
}

func (x ErrorSeverity) String() string {
	return proto.EnumName(ErrorSeverity_name, int32(x))
}

func (ErrorSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

type TransactionType int32

const (
	TransactionType_DEPOSIT            TransactionType = 0
	TransactionType_WITHDRAW           TransactionType = 1
	TransactionType_RECEIVED_TRANSFER  TransactionType = 2
	TransactionType_RECEIVED_PERFORMED TransactionType = 3
	TransactionType_LOAN               TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "DEPOSIT",
	1: "WITHDRAW",
	2: "RECEIVED_TRANSFER",
	3: "RECEIVED_PERFORMED",
	4: "LOAN",
}

var TransactionType_value = map[string]int32{
	"DEPOSIT":            0,
	"WITHDRAW":           1,
	"RECEIVED_TRANSFER":  2,
	"RECEIVED_PERFORMED": 3,
	"LOAN":               4,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 EventType            `protobuf:"varint,2,opt,name=type,proto3,enum=proto.EventType" json:"type,omitempty"`
	Data                 []byte               `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Command struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 CommandType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.CommandType" json:"type,omitempty"`
	Data                 []byte               `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_COMMAND_TYPE_UNKNOWN
}

func (m *Command) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Command) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Error struct {
	Message              string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Kind                 ErrorKind     `protobuf:"varint,2,opt,name=kind,proto3,enum=proto.ErrorKind" json:"kind,omitempty"`
	Severity             ErrorSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=proto.ErrorSeverity" json:"severity,omitempty"`
	Trace                []string      `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetKind() ErrorKind {
	if m != nil {
		return m.Kind
	}
	return ErrorKind_KIND_NOT_GIVEN
}

func (m *Error) GetSeverity() ErrorSeverity {
	if m != nil {
		return m.Severity
	}
	return ErrorSeverity_SEVERITY_NOT_GIVEN
}

func (m *Error) GetTrace() []string {
	if m != nil {
		return m.Trace
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpf                  string               `protobuf:"bytes,3,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Birthdate            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCpf() string {
	if m != nil {
		return m.Cpf
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBirthdate() *timestamp.Timestamp {
	if m != nil {
		return m.Birthdate
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Transaction struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 TransactionType      `protobuf:"varint,2,opt,name=type,proto3,enum=proto.TransactionType" json:"type,omitempty"`
	SourceAccount        string               `protobuf:"bytes,3,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	DestinyAccount       string               `protobuf:"bytes,4,opt,name=destiny_account,json=destinyAccount,proto3" json:"destiny_account,omitempty"`
	Amount               float32              `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_DEPOSIT
}

func (m *Transaction) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *Transaction) GetDestinyAccount() string {
	if m != nil {
		return m.DestinyAccount
	}
	return ""
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Account struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string               `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Owner                *User                `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              float32              `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty"`
	LastTransactions     []*Transaction       `protobuf:"bytes,5,rep,name=last_transactions,json=lastTransactions,proto3" json:"last_transactions,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Account) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetLastTransactions() []*Transaction {
	if m != nil {
		return m.LastTransactions
	}
	return nil
}

func (m *Account) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AccountCreated struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCreated) Reset()         { *m = AccountCreated{} }
func (m *AccountCreated) String() string { return proto.CompactTextString(m) }
func (*AccountCreated) ProtoMessage()    {}
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}

func (m *AccountCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreated.Unmarshal(m, b)
}
func (m *AccountCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreated.Marshal(b, m, deterministic)
}
func (m *AccountCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreated.Merge(m, src)
}
func (m *AccountCreated) XXX_Size() int {
	return xxx_messageInfo_AccountCreated.Size(m)
}
func (m *AccountCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreated.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreated proto.InternalMessageInfo

func (m *AccountCreated) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DepositRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DepositRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DepositResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositResponse) Reset()         { *m = DepositResponse{} }
func (m *DepositResponse) String() string { return proto.CompactTextString(m) }
func (*DepositResponse) ProtoMessage()    {}
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{12}
}

func (m *DepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositResponse.Unmarshal(m, b)
}
func (m *DepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositResponse.Marshal(b, m, deterministic)
}
func (m *DepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositResponse.Merge(m, src)
}
func (m *DepositResponse) XXX_Size() int {
	return xxx_messageInfo_DepositResponse.Size(m)
}
func (m *DepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositResponse proto.InternalMessageInfo

func (m *DepositResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type WithdrawRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{13}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *WithdrawRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithdrawResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{14}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TransferRequest struct {
	SourceAccountId      string   `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DeliveryAccountId    string   `protobuf:"bytes,3,opt,name=delivery_account_id,json=deliveryAccountId,proto3" json:"delivery_account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{15}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetSourceAccountId() string {
	if m != nil {
		return m.SourceAccountId
	}
	return ""
}

func (m *TransferRequest) GetDeliveryAccountId() string {
	if m != nil {
		return m.DeliveryAccountId
	}
	return ""
}

func (m *TransferRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TranseResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranseResponse) Reset()         { *m = TranseResponse{} }
func (m *TranseResponse) String() string { return proto.CompactTextString(m) }
func (*TranseResponse) ProtoMessage()    {}
func (*TranseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{16}
}

func (m *TranseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranseResponse.Unmarshal(m, b)
}
func (m *TranseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranseResponse.Marshal(b, m, deterministic)
}
func (m *TranseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranseResponse.Merge(m, src)
}
func (m *TranseResponse) XXX_Size() int {
	return xxx_messageInfo_TranseResponse.Size(m)
}
func (m *TranseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranseResponse proto.InternalMessageInfo

func (m *TranseResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LoanRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanRequest) Reset()         { *m = LoanRequest{} }
func (m *LoanRequest) String() string { return proto.CompactTextString(m) }
func (*LoanRequest) ProtoMessage()    {}
func (*LoanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{17}
}

func (m *LoanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanRequest.Unmarshal(m, b)
}
func (m *LoanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanRequest.Marshal(b, m, deterministic)
}
func (m *LoanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanRequest.Merge(m, src)
}
func (m *LoanRequest) XXX_Size() int {
	return xxx_messageInfo_LoanRequest.Size(m)
}
func (m *LoanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoanRequest proto.InternalMessageInfo

func (m *LoanRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoanRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LoanResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanResponse) Reset()         { *m = LoanResponse{} }
func (m *LoanResponse) String() string { return proto.CompactTextString(m) }
func (*LoanResponse) ProtoMessage()    {}
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{18}
}

func (m *LoanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanResponse.Unmarshal(m, b)
}
func (m *LoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanResponse.Marshal(b, m, deterministic)
}
func (m *LoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanResponse.Merge(m, src)
}
func (m *LoanResponse) XXX_Size() int {
	return xxx_messageInfo_LoanResponse.Size(m)
}
func (m *LoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoanResponse proto.InternalMessageInfo

func (m *LoanResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListAccountsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{19}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAccountsRequest) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{20}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ListAccountsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FindAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccountRequest) Reset()         { *m = FindAccountRequest{} }
func (m *FindAccountRequest) String() string { return proto.CompactTextString(m) }
func (*FindAccountRequest) ProtoMessage()    {}
func (*FindAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{21}
}

func (m *FindAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountRequest.Unmarshal(m, b)
}
func (m *FindAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountRequest.Marshal(b, m, deterministic)
}
func (m *FindAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountRequest.Merge(m, src)
}
func (m *FindAccountRequest) XXX_Size() int {
	return xxx_messageInfo_FindAccountRequest.Size(m)
}
func (m *FindAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountRequest proto.InternalMessageInfo

func (m *FindAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type FindAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccountResponse) Reset()         { *m = FindAccountResponse{} }
func (m *FindAccountResponse) String() string { return proto.CompactTextString(m) }
func (*FindAccountResponse) ProtoMessage()    {}
func (*FindAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{22}
}

func (m *FindAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountResponse.Unmarshal(m, b)
}
func (m *FindAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountResponse.Marshal(b, m, deterministic)
}
func (m *FindAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountResponse.Merge(m, src)
}
func (m *FindAccountResponse) XXX_Size() int {
	return xxx_messageInfo_FindAccountResponse.Size(m)
}
func (m *FindAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountResponse proto.InternalMessageInfo

func (m *FindAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FindAccountResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("proto.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("proto.ErrorKind", ErrorKind_name, ErrorKind_value)
	proto.RegisterEnum("proto.ErrorSeverity", ErrorSeverity_name, ErrorSeverity_value)
	proto.RegisterEnum("proto.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Command)(nil), "proto.Command")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "proto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "proto.CreateAccountResponse")
	proto.RegisterType((*AccountCreated)(nil), "proto.AccountCreated")
	proto.RegisterType((*DeleteAccountRequest)(nil), "proto.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "proto.DeleteAccountResponse")
	proto.RegisterType((*DepositRequest)(nil), "proto.DepositRequest")
	proto.RegisterType((*DepositResponse)(nil), "proto.DepositResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "proto.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "proto.WithdrawResponse")
	proto.RegisterType((*TransferRequest)(nil), "proto.TransferRequest")
	proto.RegisterType((*TranseResponse)(nil), "proto.TranseResponse")
	proto.RegisterType((*LoanRequest)(nil), "proto.LoanRequest")
	proto.RegisterType((*LoanResponse)(nil), "proto.LoanResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "proto.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "proto.ListAccountsResponse")
	proto.RegisterType((*FindAccountRequest)(nil), "proto.FindAccountRequest")
	proto.RegisterType((*FindAccountResponse)(nil), "proto.FindAccountResponse")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 1224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x72, 0xdb, 0x44,
	0x17, 0xaf, 0x6c, 0xb9, 0x89, 0x8f, 0x53, 0x5b, 0xd9, 0x38, 0xf9, 0xfc, 0xa9, 0x30, 0x0d, 0x1e,
	0xa0, 0x1e, 0x5f, 0xa4, 0x8c, 0x4b, 0x4b, 0x81, 0x61, 0x8a, 0x6a, 0x29, 0xad, 0xa6, 0xa9, 0x9c,
	0x6c, 0xe4, 0x84, 0x72, 0xa3, 0x51, 0xac, 0x4d, 0xab, 0x21, 0x96, 0x8c, 0xa4, 0xa4, 0xe3, 0x07,
	0xe0, 0x8e, 0x19, 0xca, 0x0c, 0xc3, 0xdb, 0x70, 0xcd, 0xcb, 0x30, 0x5c, 0xf1, 0x00, 0xcc, 0xae,
	0x76, 0x65, 0x59, 0x36, 0x90, 0x4c, 0xa6, 0x57, 0xd2, 0x9e, 0x7f, 0xfb, 0x3b, 0x67, 0xcf, 0xf9,
	0xed, 0xc2, 0xea, 0xe4, 0x64, 0x67, 0x12, 0x85, 0x49, 0x88, 0x2a, 0xec, 0xa3, 0xde, 0x79, 0x15,
	0x86, 0xaf, 0xce, 0xc8, 0x3d, 0xb6, 0x3a, 0x39, 0x3f, 0xbd, 0x97, 0xf8, 0x63, 0x12, 0x27, 0xee,
	0x78, 0x92, 0xda, 0xb5, 0x7f, 0x94, 0xa0, 0x62, 0x5c, 0x90, 0x20, 0x41, 0x75, 0x28, 0xf9, 0x5e,
	0x4b, 0xda, 0x96, 0x3a, 0x55, 0x5c, 0xf2, 0x3d, 0xf4, 0x21, 0xc8, 0xc9, 0x74, 0x42, 0x5a, 0xa5,
	0x6d, 0xa9, 0x53, 0xef, 0x29, 0xa9, 0xfd, 0x0e, 0xb3, 0xb5, 0xa7, 0x13, 0x82, 0x99, 0x16, 0x21,
	0x90, 0x75, 0x37, 0x71, 0x5b, 0xe5, 0x6d, 0xa9, 0xb3, 0x86, 0xd9, 0x3f, 0xfa, 0x1c, 0x60, 0x14,
	0x11, 0x37, 0x21, 0x9e, 0xe3, 0x26, 0xad, 0xc6, 0xb6, 0xd4, 0xa9, 0xf5, 0xd4, 0x9d, 0x14, 0xc9,
	0x8e, 0x40, 0xb2, 0x63, 0x0b, 0x24, 0xb8, 0xca, 0xad, 0xb5, 0xa4, 0xfd, 0x56, 0x82, 0x95, 0x7e,
	0x38, 0x1e, 0xbb, 0x81, 0xb7, 0x00, 0xe8, 0xe3, 0x39, 0x40, 0x88, 0x03, 0xe2, 0xd6, 0xef, 0x0e,
	0xd2, 0x4f, 0xb4, 0x42, 0x51, 0x14, 0x46, 0xa8, 0x05, 0x2b, 0x63, 0x12, 0xc7, 0xee, 0x2b, 0xc2,
	0x51, 0x89, 0x25, 0xad, 0xd5, 0x77, 0x7e, 0xe0, 0x15, 0x6b, 0x45, 0xbd, 0x9e, 0xfb, 0x81, 0x87,
	0x99, 0x16, 0x7d, 0x02, 0xab, 0x31, 0xb9, 0x20, 0x91, 0x9f, 0x4c, 0x19, 0xb8, 0x7a, 0xaf, 0x99,
	0xb7, 0x3c, 0xe4, 0x3a, 0x9c, 0x59, 0xa1, 0x26, 0x54, 0x92, 0xc8, 0x1d, 0x91, 0x96, 0xbc, 0x5d,
	0xee, 0x54, 0x71, 0xba, 0x68, 0xff, 0x2e, 0x81, 0x3c, 0x8c, 0x49, 0xb4, 0x50, 0x21, 0x04, 0x72,
	0xe0, 0x8e, 0xd3, 0x0a, 0x55, 0x31, 0xfb, 0x47, 0x0a, 0x94, 0x47, 0x93, 0x53, 0xb6, 0x5f, 0x15,
	0xd3, 0x5f, 0x1a, 0x94, 0x8c, 0x5d, 0xff, 0xac, 0x25, 0x33, 0x59, 0xba, 0x40, 0x8f, 0xa0, 0x7a,
	0xe2, 0x47, 0xc9, 0x6b, 0xcf, 0x4d, 0x48, 0xab, 0xf2, 0xdf, 0x05, 0xca, 0x8c, 0xaf, 0x53, 0xdb,
	0x3f, 0x24, 0xa8, 0xd9, 0x91, 0x1b, 0xc4, 0xee, 0x28, 0xf1, 0xc3, 0x60, 0x21, 0xa1, 0xee, 0xdc,
	0x91, 0x6f, 0xf1, 0x6a, 0xe5, 0x3c, 0x72, 0xc7, 0xfe, 0x11, 0xd4, 0xe3, 0xf0, 0x3c, 0x1a, 0x11,
	0xc7, 0x1d, 0x8d, 0xc2, 0xf3, 0x20, 0xe1, 0x39, 0xdf, 0x4a, 0xa5, 0x5a, 0x2a, 0x44, 0x77, 0xa1,
	0xe1, 0x91, 0x38, 0xf1, 0x83, 0x69, 0x66, 0x97, 0xd6, 0xa1, 0xce, 0xc5, 0xc2, 0x70, 0x0b, 0x6e,
	0xba, 0x63, 0xa6, 0xa7, 0xd5, 0x28, 0x61, 0xbe, 0xba, 0x4e, 0xba, 0x7f, 0x4a, 0xb0, 0x22, 0xc2,
	0x17, 0x53, 0x55, 0x61, 0x75, 0xe2, 0xc6, 0xf1, 0x9b, 0x30, 0xf2, 0xf8, 0xf9, 0x65, 0x6b, 0xf4,
	0x01, 0x54, 0xc2, 0x37, 0x01, 0x89, 0x58, 0x46, 0xb5, 0x5e, 0x8d, 0xd7, 0x81, 0xf6, 0x00, 0x4e,
	0x35, 0xb4, 0x37, 0x4f, 0xdc, 0x33, 0x37, 0x60, 0xbd, 0x42, 0xe1, 0x8a, 0x25, 0x7a, 0x0c, 0xeb,
	0x67, 0x6e, 0x9c, 0x38, 0xc9, 0xac, 0x6a, 0x71, 0xab, 0xb2, 0x5d, 0xee, 0xd4, 0xb2, 0x19, 0xca,
	0x15, 0x14, 0x2b, 0xd4, 0x38, 0x27, 0x88, 0xaf, 0x93, 0xf0, 0x67, 0xd0, 0xec, 0xb3, 0x05, 0xcf,
	0x1a, 0x93, 0xef, 0xcf, 0x49, 0x9c, 0xa0, 0x3b, 0x20, 0x9f, 0xc7, 0x24, 0x62, 0x89, 0x16, 0xf2,
	0x61, 0x8a, 0x36, 0x81, 0xcd, 0x82, 0x63, 0x3c, 0x09, 0x83, 0x98, 0xa0, 0x0e, 0xac, 0x88, 0x63,
	0x93, 0x98, 0x73, 0x9d, 0x3b, 0x0b, 0x43, 0xa1, 0x46, 0x6d, 0xa8, 0x10, 0x3a, 0x56, 0x7c, 0x93,
	0xb5, 0xfc, 0xa8, 0xe1, 0x54, 0xd5, 0xfe, 0x02, 0xea, 0xdc, 0x2f, 0xdd, 0xcd, 0xbb, 0x7c, 0xfc,
	0xf6, 0x03, 0x68, 0xea, 0xe4, 0x8c, 0x2c, 0xe4, 0xf6, 0x3e, 0x00, 0x37, 0x71, 0x7c, 0x71, 0x94,
	0x55, 0x2e, 0x31, 0xbd, 0xf6, 0x97, 0xb0, 0x59, 0x70, 0xe3, 0x99, 0x65, 0x78, 0xa5, 0x7f, 0xc6,
	0xfb, 0x14, 0xea, 0x3a, 0x99, 0x84, 0xb1, 0x7f, 0xc9, 0xdd, 0x72, 0x4d, 0x5c, 0xce, 0x37, 0x71,
	0xfb, 0x01, 0x34, 0xb2, 0x40, 0x57, 0xd8, 0xff, 0x19, 0x34, 0x8e, 0xfd, 0xe4, 0xb5, 0x17, 0xb9,
	0x6f, 0xae, 0x09, 0xe0, 0x21, 0x28, 0xb3, 0x48, 0x57, 0x40, 0xf0, 0x83, 0x04, 0x0d, 0xd6, 0x9d,
	0xa7, 0x24, 0x12, 0x10, 0xba, 0xb0, 0x3e, 0x3f, 0xf9, 0x33, 0x24, 0x8d, 0xb9, 0xe1, 0x37, 0x3d,
	0xb4, 0x03, 0x1b, 0x1e, 0x39, 0xf3, 0x2f, 0x48, 0x34, 0xcd, 0x5b, 0xa7, 0x54, 0xb1, 0x2e, 0x54,
	0xda, 0x12, 0xfc, 0xf2, 0x1c, 0xfe, 0x4f, 0xa1, 0xce, 0x60, 0x90, 0x2b, 0xa1, 0xd7, 0xa1, 0xb6,
	0x17, 0xba, 0xc1, 0x35, 0x6b, 0xd7, 0x83, 0xb5, 0x34, 0xca, 0x95, 0x4e, 0x6e, 0x63, 0xcf, 0x8f,
	0x13, 0x9e, 0x58, 0x2c, 0x10, 0x20, 0x90, 0x27, 0xe2, 0x3e, 0xab, 0x60, 0xf6, 0x4f, 0x51, 0xd1,
	0xaf, 0x93, 0x4e, 0x41, 0x89, 0x69, 0xaa, 0x54, 0xd2, 0x67, 0xbb, 0x9f, 0x42, 0x73, 0x3e, 0x12,
	0x47, 0xd1, 0x85, 0x55, 0x0e, 0x3d, 0x6e, 0x49, 0x8c, 0x5e, 0x8a, 0xa3, 0x93, 0xe9, 0x2f, 0x35,
	0x9b, 0xf7, 0x01, 0xed, 0xfa, 0x81, 0xf7, 0xaf, 0xd3, 0x25, 0x15, 0xa7, 0x6b, 0x04, 0x1b, 0x73,
	0x4e, 0xef, 0x82, 0x35, 0xba, 0x8f, 0xa0, 0x9a, 0x3d, 0x83, 0xd0, 0x16, 0x20, 0xe3, 0xc8, 0xb0,
	0x6c, 0xc7, 0x7e, 0xb9, 0x6f, 0x38, 0x43, 0xeb, 0xb9, 0x35, 0x38, 0xb6, 0x94, 0x1b, 0x68, 0x03,
	0x1a, 0x5a, 0xbf, 0x3f, 0x18, 0x5a, 0xb6, 0xd3, 0xc7, 0x86, 0x66, 0x1b, 0xba, 0x22, 0x75, 0xef,
	0x42, 0x2d, 0xf7, 0x5e, 0x41, 0x2d, 0x68, 0xf6, 0x07, 0x2f, 0x5e, 0x68, 0x96, 0x5e, 0xf0, 0xee,
	0x12, 0xa8, 0x66, 0xaf, 0x07, 0x84, 0xa0, 0xfe, 0xdc, 0xb4, 0x74, 0xc7, 0x1a, 0xd8, 0xce, 0x53,
	0xf3, 0xc8, 0xa0, 0xe1, 0x15, 0xa8, 0x3d, 0xd1, 0x74, 0x07, 0x1b, 0x07, 0x43, 0xe3, 0xd0, 0x56,
	0xde, 0x96, 0xd1, 0x3a, 0xac, 0x0d, 0x2d, 0x6d, 0x68, 0x3f, 0x1b, 0x60, 0xf3, 0x5b, 0x43, 0x57,
	0x7e, 0x2e, 0xa3, 0x3a, 0x54, 0xa9, 0xcf, 0xee, 0x60, 0x68, 0xe9, 0xca, 0x2f, 0x65, 0xd4, 0x00,
	0x18, 0x5a, 0xc6, 0x37, 0xfb, 0x46, 0x9f, 0xc2, 0xf9, 0xab, 0xdc, 0x3d, 0x86, 0x5b, 0x73, 0x4f,
	0x0f, 0x9a, 0xcd, 0xa1, 0x71, 0x64, 0x60, 0xd3, 0x7e, 0x39, 0xb7, 0xdd, 0x2a, 0xc8, 0xa6, 0xb5,
	0x3b, 0x50, 0x24, 0x54, 0x83, 0x95, 0x63, 0x0d, 0x5b, 0xa6, 0xf5, 0x54, 0x29, 0xa1, 0x2a, 0x54,
	0x0c, 0x8c, 0x07, 0x58, 0x29, 0xa3, 0x35, 0x58, 0xed, 0x63, 0xd3, 0x36, 0xfb, 0xda, 0x9e, 0x22,
	0x77, 0x09, 0x9f, 0xd2, 0xd9, 0x2d, 0x4d, 0x1d, 0x75, 0x63, 0x7f, 0x70, 0x68, 0xda, 0xca, 0x0d,
	0x6a, 0x7d, 0x6c, 0xda, 0xcf, 0x74, 0xac, 0x1d, 0x2b, 0x12, 0xda, 0x84, 0x75, 0x6c, 0xf4, 0x0d,
	0xf3, 0xc8, 0xd0, 0x1d, 0x1b, 0x6b, 0xd6, 0xe1, 0xae, 0x81, 0x95, 0x12, 0x05, 0x93, 0x89, 0xf7,
	0x0d, 0xbc, 0x3b, 0xc0, 0x2f, 0x0c, 0x5d, 0x29, 0x53, 0x30, 0x7b, 0x03, 0xcd, 0x52, 0xe4, 0xde,
	0x6f, 0x65, 0xd8, 0x12, 0x8d, 0xc8, 0x0b, 0x7b, 0x48, 0xa2, 0x0b, 0x7f, 0x44, 0xd0, 0x41, 0xe1,
	0xea, 0x11, 0xaf, 0xca, 0xdb, 0xe2, 0xdd, 0xb8, 0xe4, 0x5e, 0x52, 0xdf, 0x5b, 0xae, 0xe4, 0x5d,
	0x74, 0x50, 0x60, 0xfc, 0x62, 0xc8, 0x65, 0xd7, 0x41, 0x16, 0x72, 0x39, 0xe9, 0x3f, 0xce, 0x08,
	0x5d, 0x04, 0xdb, 0xcc, 0xec, 0xf3, 0x3c, 0xaf, 0x6e, 0x15, 0xc5, 0x3c, 0xc0, 0x93, 0x19, 0x23,
	0x8b, 0x08, 0xc2, 0xb4, 0xc0, 0xd4, 0xea, 0xff, 0x16, 0xe4, 0x3c, 0xc6, 0xd7, 0x33, 0x4a, 0x2d,
	0xc6, 0x28, 0x50, 0xad, 0xba, 0x99, 0x97, 0xcf, 0xb8, 0xef, 0x61, 0xca, 0x6b, 0xc2, 0x5b, 0xbc,
	0x2b, 0x72, 0x5c, 0xa7, 0x6e, 0xcc, 0xc9, 0x52, 0xbf, 0xde, 0xaf, 0x12, 0x34, 0xc5, 0xf9, 0x1d,
	0x9c, 0x93, 0x68, 0x2a, 0x4e, 0xef, 0x31, 0xc8, 0x94, 0x64, 0x90, 0x2a, 0xbc, 0x16, 0xb9, 0x4b,
	0xbd, 0xbd, 0x54, 0xc7, 0x11, 0x7d, 0x05, 0x32, 0x25, 0x02, 0xf4, 0x7f, 0x6e, 0xb4, 0x48, 0x25,
	0xaa, 0xba, 0x4c, 0x95, 0xba, 0x9f, 0xdc, 0x64, 0xaa, 0xfb, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xe5, 0x9c, 0xa8, 0x9f, 0x51, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountsCommandServiceClient is the client API for AccountsCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsCommandServiceClient interface {
	CreateAccountCommand(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	DeleteAccountCommand(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	DepositCommand(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	WithdrawCommand(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	TransferCommand(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TranseResponse, error)
	LoanCommand(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error)
}

type accountsCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsCommandServiceClient(cc grpc.ClientConnInterface) AccountsCommandServiceClient {
	return &accountsCommandServiceClient{cc}
}

func (c *accountsCommandServiceClient) CreateAccountCommand(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/CreateAccountCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) DeleteAccountCommand(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/DeleteAccountCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) DepositCommand(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/DepositCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) WithdrawCommand(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/WithdrawCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) TransferCommand(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TranseResponse, error) {
	out := new(TranseResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/TransferCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) LoanCommand(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error) {
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsCommandService/LoanCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsCommandServiceServer is the server API for AccountsCommandService service.
type AccountsCommandServiceServer interface {
	CreateAccountCommand(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	DeleteAccountCommand(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	DepositCommand(context.Context, *DepositRequest) (*DepositResponse, error)
	WithdrawCommand(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	TransferCommand(context.Context, *TransferRequest) (*TranseResponse, error)
	LoanCommand(context.Context, *LoanRequest) (*LoanResponse, error)
}

// UnimplementedAccountsCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsCommandServiceServer struct {
}

func (*UnimplementedAccountsCommandServiceServer) CreateAccountCommand(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) DeleteAccountCommand(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) DepositCommand(ctx context.Context, req *DepositRequest) (*DepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) WithdrawCommand(ctx context.Context, req *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) TransferCommand(ctx context.Context, req *TransferRequest) (*TranseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) LoanCommand(ctx context.Context, req *LoanRequest) (*LoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoanCommand not implemented")
}

func RegisterAccountsCommandServiceServer(s *grpc.Server, srv AccountsCommandServiceServer) {
	s.RegisterService(&_AccountsCommandService_serviceDesc, srv)
}

func _AccountsCommandService_CreateAccountCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).CreateAccountCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/CreateAccountCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).CreateAccountCommand(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_DeleteAccountCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).DeleteAccountCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/DeleteAccountCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).DeleteAccountCommand(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_DepositCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).DepositCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/DepositCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).DepositCommand(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_WithdrawCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).WithdrawCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/WithdrawCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).WithdrawCommand(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_TransferCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).TransferCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/TransferCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).TransferCommand(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_LoanCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).LoanCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsCommandService/LoanCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).LoanCommand(ctx, req.(*LoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountsCommandService",
	HandlerType: (*AccountsCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountCommand",
			Handler:    _AccountsCommandService_CreateAccountCommand_Handler,
		},
		{
			MethodName: "DeleteAccountCommand",
			Handler:    _AccountsCommandService_DeleteAccountCommand_Handler,
		},
		{
			MethodName: "DepositCommand",
			Handler:    _AccountsCommandService_DepositCommand_Handler,
		},
		{
			MethodName: "WithdrawCommand",
			Handler:    _AccountsCommandService_WithdrawCommand_Handler,
		},
		{
			MethodName: "TransferCommand",
			Handler:    _AccountsCommandService_TransferCommand_Handler,
		},
		{
			MethodName: "LoanCommand",
			Handler:    _AccountsCommandService_LoanCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

// AccountsQueryServiceClient is the client API for AccountsQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsQueryServiceClient interface {
	List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error)
}

type accountsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsQueryServiceClient(cc grpc.ClientConnInterface) AccountsQueryServiceClient {
	return &accountsQueryServiceClient{cc}
}

func (c *accountsQueryServiceClient) List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsQueryService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsQueryServiceClient) Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error) {
	out := new(FindAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountsQueryService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsQueryServiceServer is the server API for AccountsQueryService service.
type AccountsQueryServiceServer interface {
	List(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	Find(context.Context, *FindAccountRequest) (*FindAccountResponse, error)
}

// UnimplementedAccountsQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsQueryServiceServer struct {
}

func (*UnimplementedAccountsQueryServiceServer) List(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAccountsQueryServiceServer) Find(ctx context.Context, req *FindAccountRequest) (*FindAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterAccountsQueryServiceServer(s *grpc.Server, srv AccountsQueryServiceServer) {
	s.RegisterService(&_AccountsQueryService_serviceDesc, srv)
}

func _AccountsQueryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsQueryService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).List(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsQueryService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountsQueryService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).Find(ctx, req.(*FindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountsQueryService",
	HandlerType: (*AccountsQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountsQueryService_List_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _AccountsQueryService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
