// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/accounts.proto

package accounts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_DEPOSIT            TransactionType = 0
	TransactionType_WITHDRAW           TransactionType = 1
	TransactionType_RECEIVED_TRANSFER  TransactionType = 2
	TransactionType_RECEIVED_PERFORMED TransactionType = 3
	TransactionType_LOAN               TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "DEPOSIT",
	1: "WITHDRAW",
	2: "RECEIVED_TRANSFER",
	3: "RECEIVED_PERFORMED",
	4: "LOAN",
}

var TransactionType_value = map[string]int32{
	"DEPOSIT":            0,
	"WITHDRAW":           1,
	"RECEIVED_TRANSFER":  2,
	"RECEIVED_PERFORMED": 3,
	"LOAN":               4,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{0}
}

type Transaction struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 TransactionType      `protobuf:"varint,2,opt,name=type,proto3,enum=accounts.TransactionType" json:"type,omitempty"`
	SourceAccount        string               `protobuf:"bytes,3,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	DestinyAccount       string               `protobuf:"bytes,4,opt,name=destiny_account,json=destinyAccount,proto3" json:"destiny_account,omitempty"`
	Amount               float32              `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_DEPOSIT
}

func (m *Transaction) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *Transaction) GetDestinyAccount() string {
	if m != nil {
		return m.DestinyAccount
	}
	return ""
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Account struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// users.User owner = 3;
	Balance              float32              `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty"`
	LastTransactions     []*Transaction       `protobuf:"bytes,5,rep,name=last_transactions,json=lastTransactions,proto3" json:"last_transactions,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetLastTransactions() []*Transaction {
	if m != nil {
		return m.LastTransactions
	}
	return nil
}

func (m *Account) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{4}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{5}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

type DepositRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{6}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DepositRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DepositResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositResponse) Reset()         { *m = DepositResponse{} }
func (m *DepositResponse) String() string { return proto.CompactTextString(m) }
func (*DepositResponse) ProtoMessage()    {}
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{7}
}

func (m *DepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositResponse.Unmarshal(m, b)
}
func (m *DepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositResponse.Marshal(b, m, deterministic)
}
func (m *DepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositResponse.Merge(m, src)
}
func (m *DepositResponse) XXX_Size() int {
	return xxx_messageInfo_DepositResponse.Size(m)
}
func (m *DepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositResponse proto.InternalMessageInfo

type WithdrawRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{8}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *WithdrawRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithdrawResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{9}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

type TransferRequest struct {
	SourceAccountId      string   `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DeliveryAccountId    string   `protobuf:"bytes,3,opt,name=delivery_account_id,json=deliveryAccountId,proto3" json:"delivery_account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{10}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetSourceAccountId() string {
	if m != nil {
		return m.SourceAccountId
	}
	return ""
}

func (m *TransferRequest) GetDeliveryAccountId() string {
	if m != nil {
		return m.DeliveryAccountId
	}
	return ""
}

func (m *TransferRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TranseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranseResponse) Reset()         { *m = TranseResponse{} }
func (m *TranseResponse) String() string { return proto.CompactTextString(m) }
func (*TranseResponse) ProtoMessage()    {}
func (*TranseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{11}
}

func (m *TranseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranseResponse.Unmarshal(m, b)
}
func (m *TranseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranseResponse.Marshal(b, m, deterministic)
}
func (m *TranseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranseResponse.Merge(m, src)
}
func (m *TranseResponse) XXX_Size() int {
	return xxx_messageInfo_TranseResponse.Size(m)
}
func (m *TranseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranseResponse proto.InternalMessageInfo

type LoanRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanRequest) Reset()         { *m = LoanRequest{} }
func (m *LoanRequest) String() string { return proto.CompactTextString(m) }
func (*LoanRequest) ProtoMessage()    {}
func (*LoanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{12}
}

func (m *LoanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanRequest.Unmarshal(m, b)
}
func (m *LoanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanRequest.Marshal(b, m, deterministic)
}
func (m *LoanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanRequest.Merge(m, src)
}
func (m *LoanRequest) XXX_Size() int {
	return xxx_messageInfo_LoanRequest.Size(m)
}
func (m *LoanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoanRequest proto.InternalMessageInfo

func (m *LoanRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoanRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LoanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanResponse) Reset()         { *m = LoanResponse{} }
func (m *LoanResponse) String() string { return proto.CompactTextString(m) }
func (*LoanResponse) ProtoMessage()    {}
func (*LoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{13}
}

func (m *LoanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanResponse.Unmarshal(m, b)
}
func (m *LoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanResponse.Marshal(b, m, deterministic)
}
func (m *LoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanResponse.Merge(m, src)
}
func (m *LoanResponse) XXX_Size() int {
	return xxx_messageInfo_LoanResponse.Size(m)
}
func (m *LoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoanResponse proto.InternalMessageInfo

type ListAccountsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{14}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAccountsRequest) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{15}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type FindAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccountRequest) Reset()         { *m = FindAccountRequest{} }
func (m *FindAccountRequest) String() string { return proto.CompactTextString(m) }
func (*FindAccountRequest) ProtoMessage()    {}
func (*FindAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{16}
}

func (m *FindAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountRequest.Unmarshal(m, b)
}
func (m *FindAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountRequest.Marshal(b, m, deterministic)
}
func (m *FindAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountRequest.Merge(m, src)
}
func (m *FindAccountRequest) XXX_Size() int {
	return xxx_messageInfo_FindAccountRequest.Size(m)
}
func (m *FindAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountRequest proto.InternalMessageInfo

func (m *FindAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type FindAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccountResponse) Reset()         { *m = FindAccountResponse{} }
func (m *FindAccountResponse) String() string { return proto.CompactTextString(m) }
func (*FindAccountResponse) ProtoMessage()    {}
func (*FindAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{17}
}

func (m *FindAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountResponse.Unmarshal(m, b)
}
func (m *FindAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountResponse.Marshal(b, m, deterministic)
}
func (m *FindAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountResponse.Merge(m, src)
}
func (m *FindAccountResponse) XXX_Size() int {
	return xxx_messageInfo_FindAccountResponse.Size(m)
}
func (m *FindAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountResponse proto.InternalMessageInfo

func (m *FindAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterEnum("accounts.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*Transaction)(nil), "accounts.Transaction")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "accounts.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "accounts.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "accounts.DeleteAccountResponse")
	proto.RegisterType((*DepositRequest)(nil), "accounts.DepositRequest")
	proto.RegisterType((*DepositResponse)(nil), "accounts.DepositResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "accounts.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "accounts.WithdrawResponse")
	proto.RegisterType((*TransferRequest)(nil), "accounts.TransferRequest")
	proto.RegisterType((*TranseResponse)(nil), "accounts.TranseResponse")
	proto.RegisterType((*LoanRequest)(nil), "accounts.LoanRequest")
	proto.RegisterType((*LoanResponse)(nil), "accounts.LoanResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "accounts.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "accounts.ListAccountsResponse")
	proto.RegisterType((*FindAccountRequest)(nil), "accounts.FindAccountRequest")
	proto.RegisterType((*FindAccountResponse)(nil), "accounts.FindAccountResponse")
}

func init() { proto.RegisterFile("accounts/accounts.proto", fileDescriptor_5da251b36fd5e693) }

var fileDescriptor_5da251b36fd5e693 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x51, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0xc1, 0x09, 0x30, 0xa4, 0x60, 0x36, 0x40, 0x1c, 0xab, 0x49, 0x90, 0xa5, 0xaa, 0x28,
	0x55, 0x88, 0x44, 0xd4, 0x8f, 0x4a, 0xfd, 0x21, 0xd8, 0x34, 0x48, 0x69, 0x92, 0x3a, 0xa8, 0x7c,
	0x22, 0x07, 0x6f, 0x52, 0x4b, 0x60, 0xbb, 0x5e, 0x93, 0x88, 0x03, 0xf4, 0x22, 0x3d, 0x50, 0xef,
	0xd0, 0x13, 0xf4, 0x0a, 0x15, 0xeb, 0x5d, 0xdb, 0x38, 0x4e, 0x55, 0x35, 0x5f, 0x78, 0x67, 0xde,
	0xbe, 0x9d, 0x99, 0x7d, 0x6f, 0x81, 0x1d, 0x73, 0x3a, 0x75, 0x17, 0x4e, 0x40, 0x8e, 0xf9, 0x47,
	0xc7, 0xf3, 0xdd, 0xc0, 0x45, 0x45, 0xbe, 0x56, 0x0e, 0xee, 0x5c, 0xf7, 0x6e, 0x86, 0x8f, 0x69,
	0xfc, 0x66, 0x71, 0x7b, 0x1c, 0xd8, 0x73, 0x4c, 0x02, 0x73, 0xee, 0x85, 0x50, 0xf5, 0xb7, 0x00,
	0xe5, 0x91, 0x6f, 0x3a, 0xc4, 0x9c, 0x06, 0xb6, 0xeb, 0xa0, 0x0a, 0xe4, 0x6c, 0x4b, 0x16, 0x5a,
	0x42, 0xbb, 0x64, 0xe4, 0x6c, 0x0b, 0x1d, 0x81, 0x18, 0x2c, 0x3d, 0x2c, 0xe7, 0x5a, 0x42, 0xbb,
	0xd2, 0xdd, 0xed, 0x44, 0x27, 0x25, 0x36, 0x8d, 0x96, 0x1e, 0x36, 0x28, 0x0c, 0xbd, 0x86, 0x0a,
	0x71, 0x17, 0xfe, 0x14, 0x4f, 0x18, 0x50, 0xce, 0x53, 0xaa, 0x97, 0x61, 0xb4, 0x17, 0x06, 0xd1,
	0x1b, 0xa8, 0x5a, 0x98, 0x04, 0xb6, 0xb3, 0x8c, 0x70, 0x22, 0xc5, 0x55, 0x58, 0x98, 0x03, 0x9b,
	0xb0, 0x69, 0xce, 0x69, 0x7e, 0xa3, 0x25, 0xb4, 0x73, 0x06, 0x5b, 0xa1, 0xf7, 0x00, 0x53, 0x1f,
	0x9b, 0x01, 0xb6, 0x26, 0x66, 0x20, 0x57, 0x5b, 0x42, 0xbb, 0xdc, 0x55, 0x3a, 0x61, 0xb3, 0x1d,
	0xde, 0x6c, 0x67, 0xc4, 0x9b, 0x35, 0x4a, 0x0c, 0xdd, 0x0b, 0xd4, 0x9f, 0x02, 0x14, 0x38, 0x7d,
	0xba, 0x5b, 0x05, 0x8a, 0x9e, 0x49, 0xc8, 0x83, 0xeb, 0x5b, 0xb4, 0xe3, 0x92, 0x11, 0xad, 0x91,
	0x0c, 0x85, 0x1b, 0x73, 0x66, 0x3a, 0x53, 0x4c, 0x6b, 0xcd, 0x19, 0x7c, 0x89, 0x4e, 0xa1, 0x36,
	0x33, 0x49, 0x30, 0x09, 0xe2, 0x91, 0x10, 0x79, 0xa3, 0x95, 0x6f, 0x97, 0xbb, 0x8d, 0xcc, 0x81,
	0x19, 0xd2, 0x0a, 0x9f, 0x08, 0x90, 0xe7, 0x34, 0xd4, 0x84, 0x7a, 0x9f, 0x2e, 0x58, 0x57, 0x06,
	0xfe, 0xb6, 0xc0, 0x24, 0x50, 0x35, 0x68, 0xa4, 0xe2, 0xc4, 0x73, 0x1d, 0x82, 0xd1, 0x5b, 0x28,
	0xf0, 0xa9, 0x0b, 0xf4, 0xa0, 0x5a, 0x5c, 0x25, 0xc7, 0x72, 0x84, 0xfa, 0x0e, 0xea, 0x1a, 0x9e,
	0xe1, 0x34, 0x3b, 0xda, 0x03, 0x60, 0x90, 0x89, 0xcd, 0x87, 0x55, 0x62, 0x91, 0xa1, 0xa5, 0xee,
	0x40, 0x23, 0xb5, 0x2d, 0x3c, 0x5c, 0xfd, 0x08, 0x15, 0x0d, 0x7b, 0x2e, 0xb1, 0xff, 0x91, 0x29,
	0x21, 0x81, 0x7c, 0x52, 0x02, 0x6a, 0x0d, 0xaa, 0x11, 0x11, 0xe3, 0x3e, 0x83, 0xea, 0xd8, 0x0e,
	0xbe, 0x5a, 0xbe, 0xf9, 0xf0, 0x4c, 0x72, 0x04, 0x52, 0xcc, 0xc4, 0xd8, 0xbf, 0x0b, 0x50, 0xa5,
	0x77, 0x76, 0x8b, 0x7d, 0x4e, 0x7f, 0x08, 0xb5, 0x75, 0xbd, 0xc7, 0xa7, 0x54, 0xd7, 0x24, 0x3f,
	0xb4, 0x50, 0x07, 0xb6, 0x2d, 0x3c, 0xb3, 0xef, 0xb1, 0xbf, 0x4c, 0xa2, 0x43, 0x83, 0xd4, 0x78,
	0xaa, 0x97, 0x51, 0x9b, 0xb8, 0x56, 0x9b, 0x04, 0x15, 0x5a, 0x06, 0x8e, 0x2a, 0xd3, 0xa0, 0x7c,
	0xee, 0x9a, 0xce, 0x33, 0x7b, 0xae, 0xc0, 0x56, 0xc8, 0x12, 0x4d, 0x73, 0xfb, 0xdc, 0x26, 0x01,
	0x2b, 0x88, 0x70, 0x76, 0x04, 0xa2, 0x67, 0xde, 0x61, 0x2a, 0x9d, 0x0d, 0x83, 0x7e, 0xaf, 0x4e,
	0x5c, 0xfd, 0x4e, 0x42, 0x51, 0xe5, 0x68, 0xa6, 0xb4, 0x8a, 0xf4, 0x29, 0xb3, 0x0e, 0xf5, 0x75,
	0x26, 0x26, 0xc4, 0x23, 0x88, 0x5e, 0x2a, 0x59, 0xa0, 0x7e, 0xc9, 0x50, 0x62, 0x04, 0x51, 0x4f,
	0x00, 0x0d, 0x6c, 0xc7, 0xfa, 0xab, 0x10, 0x85, 0xb4, 0x10, 0x4f, 0x61, 0x7b, 0x6d, 0xd3, 0x7f,
	0x78, 0xe0, 0x10, 0xb3, 0x8b, 0x8f, 0x9f, 0x3b, 0x54, 0x86, 0x82, 0xa6, 0x5f, 0x5d, 0x5e, 0x0f,
	0x47, 0xd2, 0x0b, 0xb4, 0x05, 0xc5, 0xf1, 0x70, 0x74, 0xa6, 0x19, 0xbd, 0xb1, 0x24, 0xa0, 0x06,
	0xd4, 0x0c, 0xbd, 0xaf, 0x0f, 0xbf, 0xe8, 0xda, 0x64, 0x64, 0xf4, 0x2e, 0xae, 0x07, 0xba, 0x21,
	0xe5, 0x50, 0x13, 0x50, 0x14, 0xbe, 0xd2, 0x8d, 0xc1, 0xa5, 0xf1, 0x49, 0xd7, 0xa4, 0x3c, 0x2a,
	0x82, 0x78, 0x7e, 0xd9, 0xbb, 0x90, 0xc4, 0xee, 0xaf, 0x3c, 0x34, 0xf9, 0x8c, 0xfa, 0xee, 0x7c,
	0x6e, 0x3a, 0xd6, 0x35, 0xf6, 0xef, 0xed, 0x29, 0x46, 0xe3, 0x94, 0xc7, 0x59, 0x1a, 0xed, 0xc7,
	0x55, 0x67, 0xbd, 0x01, 0xca, 0xc1, 0x93, 0x79, 0x36, 0x87, 0x71, 0xca, 0xde, 0x19, 0xc4, 0x59,
	0xf6, 0x4f, 0x12, 0x67, 0xfa, 0x1c, 0xe9, 0x91, 0xcf, 0x39, 0xa5, 0x9c, 0xdc, 0x92, 0x7c, 0x01,
	0x94, 0xdd, 0x8c, 0x0c, 0xa3, 0x49, 0x58, 0x9a, 0xf3, 0x24, 0xd0, 0x29, 0xb7, 0x2b, 0x4a, 0x56,
	0x8a, 0x31, 0x0d, 0x62, 0xf7, 0x66, 0x30, 0xa5, 0x8c, 0xad, 0xc8, 0xa9, 0x54, 0x64, 0x36, 0xf4,
	0x21, 0x34, 0x1b, 0xe7, 0x48, 0xbc, 0xf0, 0x09, 0x0f, 0x2a, 0xcd, 0x74, 0x38, 0xdc, 0xdd, 0xfd,
	0x21, 0x40, 0x9d, 0xdf, 0xf1, 0xe7, 0x05, 0xf6, 0x97, 0xfc, 0x86, 0x75, 0x10, 0x57, 0x1e, 0x41,
	0x7b, 0x89, 0x8d, 0x8f, 0xdd, 0xa7, 0xec, 0x3f, 0x95, 0x66, 0xd5, 0xf5, 0x41, 0x5c, 0xc9, 0x1d,
	0xbd, 0x8a, 0x71, 0x8f, 0x3d, 0xa3, 0xec, 0x3d, 0x91, 0x0d, 0x49, 0x6e, 0x36, 0xe9, 0x1f, 0xce,
	0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x47, 0xed, 0x7c, 0x61, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountsCommandServiceClient is the client API for AccountsCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsCommandServiceClient interface {
	CreateAccountCommand(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	DeleteAccountCommand(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	DepositCommand(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	WithdrawCommand(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	TransferCommand(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TranseResponse, error)
	LoanCommand(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error)
}

type accountsCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsCommandServiceClient(cc grpc.ClientConnInterface) AccountsCommandServiceClient {
	return &accountsCommandServiceClient{cc}
}

func (c *accountsCommandServiceClient) CreateAccountCommand(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/CreateAccountCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) DeleteAccountCommand(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/DeleteAccountCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) DepositCommand(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/DepositCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) WithdrawCommand(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/WithdrawCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) TransferCommand(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TranseResponse, error) {
	out := new(TranseResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/TransferCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) LoanCommand(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*LoanResponse, error) {
	out := new(LoanResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/LoanCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsCommandServiceServer is the server API for AccountsCommandService service.
type AccountsCommandServiceServer interface {
	CreateAccountCommand(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	DeleteAccountCommand(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	DepositCommand(context.Context, *DepositRequest) (*DepositResponse, error)
	WithdrawCommand(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	TransferCommand(context.Context, *TransferRequest) (*TranseResponse, error)
	LoanCommand(context.Context, *LoanRequest) (*LoanResponse, error)
}

// UnimplementedAccountsCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsCommandServiceServer struct {
}

func (*UnimplementedAccountsCommandServiceServer) CreateAccountCommand(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) DeleteAccountCommand(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) DepositCommand(ctx context.Context, req *DepositRequest) (*DepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) WithdrawCommand(ctx context.Context, req *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) TransferCommand(ctx context.Context, req *TransferRequest) (*TranseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferCommand not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) LoanCommand(ctx context.Context, req *LoanRequest) (*LoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoanCommand not implemented")
}

func RegisterAccountsCommandServiceServer(s *grpc.Server, srv AccountsCommandServiceServer) {
	s.RegisterService(&_AccountsCommandService_serviceDesc, srv)
}

func _AccountsCommandService_CreateAccountCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).CreateAccountCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/CreateAccountCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).CreateAccountCommand(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_DeleteAccountCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).DeleteAccountCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/DeleteAccountCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).DeleteAccountCommand(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_DepositCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).DepositCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/DepositCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).DepositCommand(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_WithdrawCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).WithdrawCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/WithdrawCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).WithdrawCommand(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_TransferCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).TransferCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/TransferCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).TransferCommand(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_LoanCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).LoanCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/LoanCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).LoanCommand(ctx, req.(*LoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountsCommandService",
	HandlerType: (*AccountsCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountCommand",
			Handler:    _AccountsCommandService_CreateAccountCommand_Handler,
		},
		{
			MethodName: "DeleteAccountCommand",
			Handler:    _AccountsCommandService_DeleteAccountCommand_Handler,
		},
		{
			MethodName: "DepositCommand",
			Handler:    _AccountsCommandService_DepositCommand_Handler,
		},
		{
			MethodName: "WithdrawCommand",
			Handler:    _AccountsCommandService_WithdrawCommand_Handler,
		},
		{
			MethodName: "TransferCommand",
			Handler:    _AccountsCommandService_TransferCommand_Handler,
		},
		{
			MethodName: "LoanCommand",
			Handler:    _AccountsCommandService_LoanCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accounts.proto",
}

// AccountsQueryServiceClient is the client API for AccountsQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsQueryServiceClient interface {
	List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error)
}

type accountsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsQueryServiceClient(cc grpc.ClientConnInterface) AccountsQueryServiceClient {
	return &accountsQueryServiceClient{cc}
}

func (c *accountsQueryServiceClient) List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsQueryService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsQueryServiceClient) Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error) {
	out := new(FindAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsQueryService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsQueryServiceServer is the server API for AccountsQueryService service.
type AccountsQueryServiceServer interface {
	List(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	Find(context.Context, *FindAccountRequest) (*FindAccountResponse, error)
}

// UnimplementedAccountsQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsQueryServiceServer struct {
}

func (*UnimplementedAccountsQueryServiceServer) List(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAccountsQueryServiceServer) Find(ctx context.Context, req *FindAccountRequest) (*FindAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterAccountsQueryServiceServer(s *grpc.Server, srv AccountsQueryServiceServer) {
	s.RegisterService(&_AccountsQueryService_serviceDesc, srv)
}

func _AccountsQueryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsQueryService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).List(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsQueryService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsQueryService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).Find(ctx, req.(*FindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountsQueryService",
	HandlerType: (*AccountsQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountsQueryService_List_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _AccountsQueryService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accounts.proto",
}
