// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/accounts.proto

package accounts

import (
	context "context"
	errors "errors"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	users "users"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_DEPOSIT            TransactionType = 0
	TransactionType_WITHDRAW           TransactionType = 1
	TransactionType_RECEIVED_TRANSFER  TransactionType = 2
	TransactionType_RECEIVED_PERFORMED TransactionType = 3
	TransactionType_LOAN               TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "DEPOSIT",
	1: "WITHDRAW",
	2: "RECEIVED_TRANSFER",
	3: "RECEIVED_PERFORMED",
	4: "LOAN",
}

var TransactionType_value = map[string]int32{
	"DEPOSIT":            0,
	"WITHDRAW":           1,
	"RECEIVED_TRANSFER":  2,
	"RECEIVED_PERFORMED": 3,
	"LOAN":               4,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{0}
}

type Transaction struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 TransactionType      `protobuf:"varint,2,opt,name=type,proto3,enum=accounts.TransactionType" json:"type,omitempty"`
	SourceAccount        string               `protobuf:"bytes,3,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	DestinyAccount       string               `protobuf:"bytes,4,opt,name=destiny_account,json=destinyAccount,proto3" json:"destiny_account,omitempty"`
	Amount               float32              `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_DEPOSIT
}

func (m *Transaction) GetSourceAccount() string {
	if m != nil {
		return m.SourceAccount
	}
	return ""
}

func (m *Transaction) GetDestinyAccount() string {
	if m != nil {
		return m.DestinyAccount
	}
	return ""
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Account struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string               `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Owner                *users.User          `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              float32              `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty"`
	LastTransactions     []*Transaction       `protobuf:"bytes,5,rep,name=last_transactions,json=lastTransactions,proto3" json:"last_transactions,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetOwner() *users.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Account) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetLastTransactions() []*Transaction {
	if m != nil {
		return m.LastTransactions
	}
	return nil
}

func (m *Account) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ErrorResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{2}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateAccountRequest struct {
	User                 *users.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{3}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUser() *users.User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateAccountResponse struct {
	Account              *Account      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error                *errors.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{4}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteAccountRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{5}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DepositRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{6}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DepositRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithdrawRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{7}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *WithdrawRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransferRequest struct {
	SourceAccountId      string   `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	DeliveryAccountId    string   `protobuf:"bytes,3,opt,name=delivery_account_id,json=deliveryAccountId,proto3" json:"delivery_account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{8}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetSourceAccountId() string {
	if m != nil {
		return m.SourceAccountId
	}
	return ""
}

func (m *TransferRequest) GetDeliveryAccountId() string {
	if m != nil {
		return m.DeliveryAccountId
	}
	return ""
}

func (m *TransferRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LoanRequest struct {
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanRequest) Reset()         { *m = LoanRequest{} }
func (m *LoanRequest) String() string { return proto.CompactTextString(m) }
func (*LoanRequest) ProtoMessage()    {}
func (*LoanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{9}
}

func (m *LoanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanRequest.Unmarshal(m, b)
}
func (m *LoanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanRequest.Marshal(b, m, deterministic)
}
func (m *LoanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanRequest.Merge(m, src)
}
func (m *LoanRequest) XXX_Size() int {
	return xxx_messageInfo_LoanRequest.Size(m)
}
func (m *LoanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoanRequest proto.InternalMessageInfo

func (m *LoanRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoanRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ListAccountsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{10}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAccountsRequest) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type ListAccountsResponse struct {
	Accounts             []*Account    `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Error                *errors.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{11}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ListAccountsResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FindAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAccountRequest) Reset()         { *m = FindAccountRequest{} }
func (m *FindAccountRequest) String() string { return proto.CompactTextString(m) }
func (*FindAccountRequest) ProtoMessage()    {}
func (*FindAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{12}
}

func (m *FindAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountRequest.Unmarshal(m, b)
}
func (m *FindAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountRequest.Marshal(b, m, deterministic)
}
func (m *FindAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountRequest.Merge(m, src)
}
func (m *FindAccountRequest) XXX_Size() int {
	return xxx_messageInfo_FindAccountRequest.Size(m)
}
func (m *FindAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountRequest proto.InternalMessageInfo

func (m *FindAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type FindAccountResponse struct {
	Account              *Account      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error                *errors.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindAccountResponse) Reset()         { *m = FindAccountResponse{} }
func (m *FindAccountResponse) String() string { return proto.CompactTextString(m) }
func (*FindAccountResponse) ProtoMessage()    {}
func (*FindAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{13}
}

func (m *FindAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAccountResponse.Unmarshal(m, b)
}
func (m *FindAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAccountResponse.Marshal(b, m, deterministic)
}
func (m *FindAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAccountResponse.Merge(m, src)
}
func (m *FindAccountResponse) XXX_Size() int {
	return xxx_messageInfo_FindAccountResponse.Size(m)
}
func (m *FindAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAccountResponse proto.InternalMessageInfo

func (m *FindAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FindAccountResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("accounts.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*Transaction)(nil), "accounts.Transaction")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*ErrorResponse)(nil), "accounts.ErrorResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "accounts.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "accounts.DeleteAccountRequest")
	proto.RegisterType((*DepositRequest)(nil), "accounts.DepositRequest")
	proto.RegisterType((*WithdrawRequest)(nil), "accounts.WithdrawRequest")
	proto.RegisterType((*TransferRequest)(nil), "accounts.TransferRequest")
	proto.RegisterType((*LoanRequest)(nil), "accounts.LoanRequest")
	proto.RegisterType((*ListAccountsRequest)(nil), "accounts.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "accounts.ListAccountsResponse")
	proto.RegisterType((*FindAccountRequest)(nil), "accounts.FindAccountRequest")
	proto.RegisterType((*FindAccountResponse)(nil), "accounts.FindAccountResponse")
}

func init() { proto.RegisterFile("accounts/accounts.proto", fileDescriptor_5da251b36fd5e693) }

var fileDescriptor_5da251b36fd5e693 = []byte{
	// 829 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xeb, 0x6e, 0xe2, 0x46,
	0x14, 0xae, 0x8d, 0x09, 0x70, 0xdc, 0x70, 0x19, 0x48, 0xd6, 0xb5, 0x9a, 0x0d, 0xa5, 0xaa, 0x8a,
	0xb6, 0x5a, 0x23, 0xb1, 0xbd, 0xa8, 0x52, 0x55, 0x89, 0x82, 0xd3, 0x45, 0x4a, 0x37, 0xdb, 0x09,
	0x6d, 0x7e, 0x22, 0x07, 0xcf, 0x52, 0x57, 0x60, 0xbb, 0x33, 0x66, 0x23, 0x1e, 0xa0, 0x6f, 0xd1,
	0x5f, 0x7d, 0xc1, 0xaa, 0x6f, 0x50, 0x79, 0x2e, 0xd8, 0x10, 0x88, 0x22, 0x45, 0xfd, 0x03, 0xf6,
	0x39, 0xdf, 0xf9, 0xe6, 0xdc, 0xbe, 0x31, 0x3c, 0xf3, 0x66, 0xb3, 0x68, 0x15, 0x26, 0xac, 0xa7,
	0x1e, 0x9c, 0x98, 0x46, 0x49, 0x84, 0xca, 0xea, 0xdd, 0x3e, 0x9f, 0x47, 0xd1, 0x7c, 0x41, 0x7a,
	0xdc, 0x7e, 0xbb, 0x7a, 0xd7, 0x4b, 0x82, 0x25, 0x61, 0x89, 0xb7, 0x8c, 0x05, 0xd4, 0x6e, 0xac,
	0x18, 0xa1, 0xac, 0xc7, 0x7f, 0xa5, 0xa9, 0x49, 0x28, 0x8d, 0x28, 0xeb, 0x89, 0x3f, 0x61, 0xec,
	0xfc, 0xa3, 0x81, 0x39, 0xa1, 0x5e, 0xc8, 0xbc, 0x59, 0x12, 0x44, 0x21, 0xaa, 0x82, 0x1e, 0xf8,
	0x96, 0xd6, 0xd6, 0xba, 0x15, 0xac, 0x07, 0x3e, 0x7a, 0x09, 0x46, 0xb2, 0x8e, 0x89, 0xa5, 0xb7,
	0xb5, 0x6e, 0xb5, 0xff, 0x91, 0xb3, 0xc9, 0x28, 0x17, 0x34, 0x59, 0xc7, 0x04, 0x73, 0x18, 0xfa,
	0x0c, 0xaa, 0x2c, 0x5a, 0xd1, 0x19, 0x99, 0x4a, 0xa0, 0x55, 0xe0, 0x54, 0xc7, 0xc2, 0x3a, 0x10,
	0x46, 0xf4, 0x39, 0xd4, 0x7c, 0xc2, 0x92, 0x20, 0x5c, 0x6f, 0x70, 0x06, 0xc7, 0x55, 0xa5, 0x59,
	0x01, 0x4f, 0xe1, 0xc8, 0x5b, 0x72, 0x7f, 0xb1, 0xad, 0x75, 0x75, 0x2c, 0xdf, 0xd0, 0xb7, 0x00,
	0x33, 0x4a, 0xbc, 0x84, 0xf8, 0x53, 0x2f, 0xb1, 0x6a, 0x6d, 0xad, 0x6b, 0xf6, 0x6d, 0x47, 0x34,
	0xc5, 0x51, 0x4d, 0x71, 0x26, 0xaa, 0x29, 0xb8, 0x22, 0xd1, 0x83, 0xa4, 0xf3, 0xaf, 0x06, 0x25,
	0x45, 0xbf, 0x5b, 0xad, 0x0d, 0xe5, 0xd8, 0x63, 0xec, 0x2e, 0xa2, 0x3e, 0xaf, 0xb8, 0x82, 0x37,
	0xef, 0xe8, 0x13, 0x28, 0x46, 0x77, 0x21, 0xa1, 0xbc, 0x22, 0xb3, 0x6f, 0x3a, 0xa2, 0xb7, 0xbf,
	0x30, 0x42, 0xb1, 0xf0, 0x20, 0x0b, 0x4a, 0xb7, 0xde, 0xc2, 0x0b, 0x67, 0x84, 0x97, 0xa3, 0x63,
	0xf5, 0x8a, 0x7e, 0x80, 0xc6, 0xc2, 0x63, 0xc9, 0x34, 0xc9, 0xba, 0xc6, 0xac, 0x62, 0xbb, 0xd0,
	0x35, 0xfb, 0x27, 0x7b, 0x7b, 0x8a, 0xeb, 0x29, 0x3e, 0x67, 0x60, 0x4f, 0xa9, 0xf9, 0x4b, 0x38,
	0x76, 0xd3, 0xa9, 0x63, 0xc2, 0xe2, 0x28, 0x64, 0x04, 0x7d, 0x0a, 0x45, 0xbe, 0x06, 0xbc, 0x76,
	0xb3, 0x7f, 0xec, 0xc8, 0xa5, 0x10, 0x28, 0xe1, 0xeb, 0x7c, 0x03, 0xad, 0x21, 0xa7, 0x90, 0xed,
	0xc2, 0xe4, 0x8f, 0x15, 0x61, 0x09, 0x3a, 0x07, 0x23, 0xad, 0x9d, 0x77, 0x68, 0xa7, 0x11, 0xdc,
	0xd1, 0x09, 0xe0, 0x64, 0x27, 0x50, 0x1e, 0xfb, 0x05, 0x94, 0xd4, 0xbc, 0xc5, 0xc1, 0x8d, 0xac,
	0x78, 0x85, 0x55, 0x88, 0x2c, 0x47, 0xfd, 0x81, 0x1c, 0xbf, 0x82, 0xd6, 0x88, 0x2c, 0xc8, 0xbd,
	0x1c, 0xcf, 0x00, 0x24, 0xcf, 0x34, 0x50, 0xb3, 0xac, 0x48, 0xcb, 0xd8, 0xef, 0xfc, 0x08, 0xd5,
	0x11, 0x89, 0x23, 0x16, 0x3c, 0x32, 0x20, 0xb7, 0x88, 0x85, 0xfc, 0x22, 0x76, 0x5e, 0x43, 0xed,
	0x26, 0x48, 0x7e, 0xf3, 0xa9, 0x77, 0xf7, 0x44, 0xa6, 0x3f, 0x35, 0xa8, 0xf1, 0x79, 0xbf, 0x23,
	0x54, 0x51, 0xbd, 0x80, 0xc6, 0xb6, 0x9c, 0x32, 0xc6, 0xda, 0x96, 0xa2, 0xc6, 0x3e, 0x72, 0xa0,
	0xe9, 0x93, 0x45, 0xf0, 0x9e, 0xd0, 0x75, 0x1e, 0x2d, 0xf4, 0xd7, 0x50, 0xae, 0xc1, 0x9e, 0x3c,
	0x8c, 0xad, 0x3c, 0x46, 0x60, 0x5e, 0x46, 0x5e, 0xf8, 0xe4, 0xbe, 0x34, 0x2f, 0x03, 0x96, 0xc8,
	0xe3, 0x98, 0x62, 0x43, 0x60, 0xc4, 0xde, 0x9c, 0xf0, 0xe9, 0x17, 0x31, 0x7f, 0x4e, 0x4f, 0x48,
	0xff, 0xa7, 0x62, 0x2f, 0x74, 0xee, 0xa9, 0xa4, 0x96, 0x21, 0x67, 0xfa, 0x1d, 0x5a, 0xdb, 0x4c,
	0x72, 0x97, 0x5e, 0xc2, 0xe6, 0x3a, 0xb4, 0x34, 0xae, 0xa4, 0x3d, 0xcb, 0xb4, 0x81, 0x3c, 0x6e,
	0x9b, 0x5e, 0x01, 0xba, 0x08, 0x42, 0xff, 0xc1, 0x5d, 0xd2, 0x76, 0x77, 0x69, 0x0e, 0xcd, 0xad,
	0xa0, 0xff, 0x6b, 0xd7, 0x5f, 0x10, 0xb9, 0x20, 0xd9, 0xad, 0x8b, 0x4c, 0x28, 0x8d, 0xdc, 0xb7,
	0x57, 0xd7, 0xe3, 0x49, 0xfd, 0x03, 0xf4, 0x21, 0x94, 0x6f, 0xc6, 0x93, 0xd7, 0x23, 0x3c, 0xb8,
	0xa9, 0x6b, 0xe8, 0x04, 0x1a, 0xd8, 0x1d, 0xba, 0xe3, 0x5f, 0xdd, 0xd1, 0x74, 0x82, 0x07, 0x6f,
	0xae, 0x2f, 0x5c, 0x5c, 0xd7, 0xd1, 0x29, 0xa0, 0x8d, 0xf9, 0xad, 0x8b, 0x2f, 0xae, 0xf0, 0x4f,
	0xee, 0xa8, 0x5e, 0x40, 0x65, 0x30, 0x2e, 0xaf, 0x06, 0x6f, 0xea, 0x46, 0xff, 0xaf, 0x02, 0x9c,
	0xaa, 0x6e, 0x0f, 0xa3, 0xe5, 0xd2, 0x0b, 0xfd, 0x6b, 0x42, 0xdf, 0x07, 0x33, 0x82, 0xc6, 0x70,
	0x24, 0x84, 0x8d, 0x9e, 0x67, 0xc5, 0xec, 0xbb, 0x23, 0xec, 0xf3, 0x83, 0x7e, 0xd9, 0x9e, 0x01,
	0x1c, 0x09, 0xe1, 0xe6, 0xa9, 0xf6, 0x49, 0xd9, 0x7e, 0x96, 0xf9, 0xb7, 0x2f, 0xb1, 0xef, 0xa0,
	0x24, 0x45, 0x8c, 0xac, 0x3c, 0x47, 0x5e, 0xd7, 0x87, 0xa3, 0xbf, 0x87, 0xb2, 0x52, 0x2e, 0xca,
	0x7d, 0xd7, 0x76, 0xd4, 0xfc, 0x60, 0xbc, 0x92, 0x2b, 0xda, 0xfd, 0x2e, 0x66, 0x12, 0x3e, 0x1c,
	0xff, 0x35, 0x18, 0xa9, 0xce, 0x50, 0xee, 0xfe, 0xcf, 0xe9, 0xee, 0x60, 0x5c, 0xff, 0x6f, 0x0d,
	0x5a, 0x6a, 0x3c, 0x3f, 0xaf, 0x08, 0x5d, 0xab, 0xe1, 0xb8, 0x60, 0xa4, 0x42, 0x41, 0x67, 0x39,
	0xc2, 0xfb, 0x12, 0xb4, 0x9f, 0x1f, 0x72, 0xcb, 0xbc, 0x86, 0x60, 0xa4, 0xeb, 0x8c, 0x3e, 0xce,
	0x70, 0xf7, 0x35, 0x61, 0x9f, 0x1d, 0xf0, 0x0a, 0x92, 0xdb, 0x23, 0xfe, 0x3d, 0x7a, 0xf5, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x60, 0x22, 0xec, 0xcb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountsCommandServiceClient is the client API for AccountsCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsCommandServiceClient interface {
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	Loan(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type accountsCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsCommandServiceClient(cc grpc.ClientConnInterface) AccountsCommandServiceClient {
	return &accountsCommandServiceClient{cc}
}

func (c *accountsCommandServiceClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsCommandServiceClient) Loan(ctx context.Context, in *LoanRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsCommandService/Loan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsCommandServiceServer is the server API for AccountsCommandService service.
type AccountsCommandServiceServer interface {
	Create(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	Delete(context.Context, *DeleteAccountRequest) (*ErrorResponse, error)
	Deposit(context.Context, *DepositRequest) (*ErrorResponse, error)
	Withdraw(context.Context, *WithdrawRequest) (*ErrorResponse, error)
	Transfer(context.Context, *TransferRequest) (*ErrorResponse, error)
	Loan(context.Context, *LoanRequest) (*ErrorResponse, error)
}

// UnimplementedAccountsCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsCommandServiceServer struct {
}

func (*UnimplementedAccountsCommandServiceServer) Create(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) Delete(ctx context.Context, req *DeleteAccountRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) Deposit(ctx context.Context, req *DepositRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) Withdraw(ctx context.Context, req *WithdrawRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) Transfer(ctx context.Context, req *TransferRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (*UnimplementedAccountsCommandServiceServer) Loan(ctx context.Context, req *LoanRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Loan not implemented")
}

func RegisterAccountsCommandServiceServer(s *grpc.Server, srv AccountsCommandServiceServer) {
	s.RegisterService(&_AccountsCommandService_serviceDesc, srv)
}

func _AccountsCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Delete(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsCommandService_Loan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsCommandServiceServer).Loan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsCommandService/Loan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsCommandServiceServer).Loan(ctx, req.(*LoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountsCommandService",
	HandlerType: (*AccountsCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountsCommandService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountsCommandService_Delete_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _AccountsCommandService_Deposit_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _AccountsCommandService_Withdraw_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _AccountsCommandService_Transfer_Handler,
		},
		{
			MethodName: "Loan",
			Handler:    _AccountsCommandService_Loan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accounts.proto",
}

// AccountsQueryServiceClient is the client API for AccountsQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsQueryServiceClient interface {
	List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error)
}

type accountsQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsQueryServiceClient(cc grpc.ClientConnInterface) AccountsQueryServiceClient {
	return &accountsQueryServiceClient{cc}
}

func (c *accountsQueryServiceClient) List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsQueryService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsQueryServiceClient) Find(ctx context.Context, in *FindAccountRequest, opts ...grpc.CallOption) (*FindAccountResponse, error) {
	out := new(FindAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountsQueryService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsQueryServiceServer is the server API for AccountsQueryService service.
type AccountsQueryServiceServer interface {
	List(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	Find(context.Context, *FindAccountRequest) (*FindAccountResponse, error)
}

// UnimplementedAccountsQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsQueryServiceServer struct {
}

func (*UnimplementedAccountsQueryServiceServer) List(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAccountsQueryServiceServer) Find(ctx context.Context, req *FindAccountRequest) (*FindAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterAccountsQueryServiceServer(s *grpc.Server, srv AccountsQueryServiceServer) {
	s.RegisterService(&_AccountsQueryService_serviceDesc, srv)
}

func _AccountsQueryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsQueryService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).List(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsQueryService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsQueryServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsQueryService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsQueryServiceServer).Find(ctx, req.(*FindAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountsQueryService",
	HandlerType: (*AccountsQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountsQueryService_List_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _AccountsQueryService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accounts.proto",
}
