// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors/errors.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorKind int32

const (
	ErrorKind_KIND_NOT_GIVEN ErrorKind = 0
	ErrorKind_BAD_REQUEST    ErrorKind = 400
	ErrorKind_UNAUTHORIZED   ErrorKind = 401
	ErrorKind_NOT_FOUND      ErrorKind = 404
	ErrorKind_UNEXPECTED     ErrorKind = 500
)

var ErrorKind_name = map[int32]string{
	0:   "KIND_NOT_GIVEN",
	400: "BAD_REQUEST",
	401: "UNAUTHORIZED",
	404: "NOT_FOUND",
	500: "UNEXPECTED",
}

var ErrorKind_value = map[string]int32{
	"KIND_NOT_GIVEN": 0,
	"BAD_REQUEST":    400,
	"UNAUTHORIZED":   401,
	"NOT_FOUND":      404,
	"UNEXPECTED":     500,
}

func (x ErrorKind) String() string {
	return proto.EnumName(ErrorKind_name, int32(x))
}

func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85c4eef3398a32b2, []int{0}
}

type ErrorSeverity int32

const (
	ErrorSeverity_SEVERITY_NOT_GIVEN ErrorSeverity = 0
	ErrorSeverity_INFO               ErrorSeverity = 1
	ErrorSeverity_WARNING            ErrorSeverity = 2
	ErrorSeverity_ERROR              ErrorSeverity = 3
	ErrorSeverity_CRITICAL           ErrorSeverity = 4
)

var ErrorSeverity_name = map[int32]string{
	0: "SEVERITY_NOT_GIVEN",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
	4: "CRITICAL",
}

var ErrorSeverity_value = map[string]int32{
	"SEVERITY_NOT_GIVEN": 0,
	"INFO":               1,
	"WARNING":            2,
	"ERROR":              3,
	"CRITICAL":           4,
}

func (x ErrorSeverity) String() string {
	return proto.EnumName(ErrorSeverity_name, int32(x))
}

func (ErrorSeverity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85c4eef3398a32b2, []int{1}
}

type Error struct {
	Message              string        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Kind                 ErrorKind     `protobuf:"varint,2,opt,name=kind,proto3,enum=errors.ErrorKind" json:"kind,omitempty"`
	Severity             ErrorSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=errors.ErrorSeverity" json:"severity,omitempty"`
	Trace                []string      `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_85c4eef3398a32b2, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetKind() ErrorKind {
	if m != nil {
		return m.Kind
	}
	return ErrorKind_KIND_NOT_GIVEN
}

func (m *Error) GetSeverity() ErrorSeverity {
	if m != nil {
		return m.Severity
	}
	return ErrorSeverity_SEVERITY_NOT_GIVEN
}

func (m *Error) GetTrace() []string {
	if m != nil {
		return m.Trace
	}
	return nil
}

func init() {
	proto.RegisterEnum("errors.ErrorKind", ErrorKind_name, ErrorKind_value)
	proto.RegisterEnum("errors.ErrorSeverity", ErrorSeverity_name, ErrorSeverity_value)
	proto.RegisterType((*Error)(nil), "errors.Error")
}

func init() { proto.RegisterFile("errors/errors.proto", fileDescriptor_85c4eef3398a32b2) }

var fileDescriptor_85c4eef3398a32b2 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xdf, 0x4a, 0x02, 0x41,
	0x14, 0xc6, 0x5b, 0x67, 0xfd, 0xb3, 0x47, 0xb3, 0xf1, 0xf4, 0x87, 0xbd, 0x94, 0x20, 0x10, 0x2f,
	0x8c, 0xea, 0x09, 0x36, 0x77, 0xb4, 0xc1, 0x98, 0xad, 0xe3, 0xac, 0x56, 0x37, 0x62, 0x39, 0x84,
	0x44, 0x1a, 0xb3, 0x12, 0xf4, 0x16, 0x09, 0x3d, 0x6a, 0x0f, 0x10, 0xee, 0x9a, 0xb0, 0x57, 0x33,
	0x1f, 0xdf, 0xef, 0xfb, 0xce, 0xe1, 0xc0, 0xa1, 0xb1, 0x76, 0x69, 0x93, 0xf3, 0xec, 0xe9, 0x7c,
	0xd8, 0xe5, 0x6a, 0x89, 0xa5, 0x4c, 0x9d, 0xae, 0x1d, 0x28, 0x8a, 0xcd, 0x17, 0x7d, 0x28, 0xbf,
	0x9b, 0x24, 0x99, 0xbe, 0x1a, 0xdf, 0x69, 0x3a, 0x2d, 0x8f, 0xfe, 0x25, 0x9e, 0x81, 0xfb, 0x36,
	0x5f, 0xcc, 0xfc, 0x42, 0xd3, 0x69, 0xd5, 0x2f, 0x1b, 0x9d, 0x6d, 0x51, 0x1a, 0x1b, 0xcc, 0x17,
	0x33, 0x4a, 0x6d, 0xbc, 0x80, 0x4a, 0x62, 0x3e, 0x8d, 0x9d, 0xaf, 0xbe, 0x7c, 0x96, 0xa2, 0xc7,
	0x39, 0x74, 0xb8, 0x35, 0x69, 0x87, 0xe1, 0x11, 0x14, 0x57, 0x76, 0xfa, 0x62, 0x7c, 0xb7, 0xc9,
	0x5a, 0x1e, 0x65, 0xa2, 0x6d, 0xc0, 0xdb, 0x75, 0x23, 0x42, 0x7d, 0x20, 0x55, 0x38, 0x51, 0x91,
	0x9e, 0xf4, 0xe5, 0x48, 0x28, 0xbe, 0x87, 0x1c, 0xaa, 0xd7, 0x41, 0x38, 0x21, 0x71, 0x1f, 0x8b,
	0xa1, 0xe6, 0xdf, 0x0c, 0x1b, 0x50, 0x8b, 0x55, 0x10, 0xeb, 0x9b, 0x88, 0xe4, 0x93, 0x08, 0xf9,
	0x9a, 0x61, 0x1d, 0xbc, 0x4d, 0xa6, 0x17, 0xc5, 0x2a, 0xe4, 0x3f, 0x0c, 0x0f, 0x00, 0x62, 0x25,
	0x1e, 0xee, 0x44, 0x57, 0x8b, 0x90, 0xff, 0xb2, 0xf6, 0x18, 0xf6, 0x73, 0x7b, 0xe1, 0x09, 0xe0,
	0x50, 0x8c, 0x04, 0x49, 0xfd, 0x98, 0x1b, 0x57, 0x01, 0x57, 0xaa, 0x5e, 0xc4, 0x1d, 0xac, 0x42,
	0x79, 0x1c, 0x90, 0x92, 0xaa, 0xcf, 0x0b, 0xe8, 0x41, 0x51, 0x10, 0x45, 0xc4, 0x19, 0xd6, 0xa0,
	0xd2, 0x25, 0xa9, 0x65, 0x37, 0xb8, 0xe5, 0xee, 0x73, 0x29, 0x3d, 0xf1, 0xd5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0x73, 0x26, 0x4f, 0x79, 0x01, 0x00, 0x00,
}
